# zkmoon is testnet for zklink
[contracts]
CREATE2_FACTORY_ADDR=0x40fcee4450B3DA99Da62a37aB80385cFAF5328EB
L1_MULTICALL3_ADDR=0xa2e77C99f68F21c300A82a733e43c4d8AF6344dC

[eth_sender]
[eth_sender.sender]
proof_sending_mode="OnlyRealProofs"
max_aggregated_tx_gas=100000000
proof_loading_mode="FriProofFromGcs"
