# zktitan: deploy on linea goerli testnet
[contracts]
CREATE2_FACTORY_ADDR="0x8BaCfa1f4CE7f75095127e921F2Cda03786EacD6"
L1_MULTICALL3_ADDR="0x45Fc42acD099c3e3A1d3e9fD9E5548Be66e97252"

[api.web3_json_rpc]
max_tx_size=1000000

[chain.state_keeper]
proof_sending_mode="SkipEveryProof"
# tx number limit
transaction_slots=1500
miniblock_commit_deadline_ms=2000
block_commit_deadline_ms=600000
max_gas_per_batch=5000000
# tx gas limit
max_single_tx_gas=4000000
close_block_at_gas_percentage=0.95
reject_tx_at_gas_percentage=0.95
# tx size limit: default 60000(59kb)
close_block_at_eth_params_percentage=0.95
reject_tx_at_eth_params_percentage=0.95
# zkevm circuit limit
close_block_at_geometry_percentage=0.95
reject_tx_at_geometry_percentage=0.95
# calculate fee
max_pubdata_per_batch=100000

[eth_sender]
[eth_sender.sender]
max_aggregated_tx_gas=5000000
max_eth_tx_data_size=59000
tx_poll_period=60
aggregate_tx_poll_period=60
proof_loading_mode="FriProofFromGcs"
