name: Workflow template for CI jobs to be ran on both Prover and Core Components
on:
  workflow_call:

jobs:
  build:
    runs-on: [matterlabs-ci-runner]
    env:
      RUNNER_COMPOSE_FILE: "docker-compose-runner-nightly.yml"

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          submodules: "recursive"

      - name: Setup environment
        run: |
          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH
          echo IN_DOCKER=1 >> .env

      - name: Start services
        run: |
          docker-compose -f ${RUNNER_COMPOSE_FILE} pull
          mkdir -p ./volumes/postgres
          docker-compose -f ${RUNNER_COMPOSE_FILE} up --build -d zk postgres
          ci_run sccache --start-server

      - name: Init
        run: |
          ci_run zk
          ci_run zk db setup

      - name: Lints
        run: ci_run zk lint prover
